services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 1000:1000
    volumes:
      - .jellyfin/config:/config
      - .jellyfin/cache:/cache
      - ~/media/storage:/media:ro
    restart: always
    runtime: nvidia
    env_file:
      - .env
    networks:
      - homelab-network

networks:
  homelab-network:
    external: true
