services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - .open-webui:/app/backend/data
    restart: always
    networks:
      - homelab-network

networks:
  homelab-network:
    external: true
