services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./.pihole:/etc/pihole
    networks:
      - pihole-network
      - homelab-network
    dns:
      - 1.1.1.1
      - 1.0.0.1

  pihole-tailscale:
    container_name: pihole-tailscale
    image: tailscale/tailscale:latest    
    restart: unless-stopped
    depends_on:
      - pihole
    env_file:
      - .env
    volumes:
      - ./.tailscale:/var/lib/tailscale
      - ./dnsmasq.conf:/tmp/dnsmasq.conf
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    networks:
      - pihole-network
    dns:
      - 1.1.1.1
      - 1.0.0.1
    command: >
      sh -c "
        apk add --no-cache dnsmasq &&
        until nc -z pihole 53; do sleep 2; done &&
        dnsmasq --conf-file=/tmp/dnsmasq.conf --no-daemon &
        exec /usr/local/bin/containerboot
      "

networks:
  pihole-network:
  homelab-network:
    external: true

