services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4141:80/tcp"
    env_file:
      - .env
    volumes:
      - './.pihole:/etc/pihole'
