services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    volumes:
      - .ollama:/root/.ollama
    runtime: nvidia
    env_file:
      - .env
    networks:
      - homelab-network

volumes:
  ollama:

networks:
  homelab-network:
    external: true
