services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm
    restart: unless-stopped
    volumes:
      - .vllm:/root/.cache/huggingface
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: [
      "--model", "yanolja/YanoljaNEXT-Rosetta-4B",
      "--host", "0.0.0.0",
      "--port", "8000"
    ]
    networks:
      - homelab-network

networks:
  homelab-network:
    external: true

