services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm
    restart: always
    volumes:
      - .vllm:/root/.cache/huggingface
    runtime: nvidia
    env_file:
      - .env
    command: [
      "--model", "yanolja/YanoljaNEXT-Rosetta-12B",
      "--host", "0.0.0.0",
      "--port", "8000"
    ]
    networks:
      - homelab-network

networks:
  homelab-network:
    external: true

